version: "3.7"
services:
  database:
    container_name: postgres
    image: postgres:13.3
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mlflow
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: supersafe
    ports:
      - 5432:5432
  storage:
    container_name: minio
    image: minio/minio:latest
    restart: always
    entrypoint: sh
    command: -c 'mkdir -p /storage/mlflow && minio server /storage'
    volumes:
      - ./storage:/storage
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: supersafe
    ports:
      - 9000:9000
  mlflow:
    container_name: mlflow
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      BACKEND_STORE_URI: postgresql+psycopg2://admin:supersafe@database:5432/mlflow
      ARTIFACT_ROOT: s3://mlflow
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: supersafe
      MLFLOW_S3_ENDPOINT_URL: http://storage:9000
    depends_on:
      - database
      - storage
    ports:
      - 5000:5000
