name: Hadolint
on: [push, pull_request]
jobs:
  check-dockerfiles:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hadolint/hadolint-action@v2.1.0
      with:
        recursive: true
        failure-threshold: error
